id: fab59021-39d7-466a-a577-0949593c0af2
# Name of the quickstart (required)
name: new-rest-quickstart

# Displayed in the UI (required)
title: TEST Quickstart

# Long-form description of the quickstart (required)
description: |
  The template quickstart allows you to get visibility into the performance and available of your example service and dependencies. Use this quickstart together with the mock up integrations.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  A short form description for this quickstart

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - John Smith

# Keywords for filtering / searching criteria in the UI
keywords:
  - list
  - of
  - searchable
  - keywords

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - infra-test-2

documentation:
  - name: Installation Docs
    url: https://docs.newrelic.com
    description: Description about this doc reference

# Content / Design
logo: logo.png
website: https://www.newrelic.com
