name: New PR

on:
  pull_request_target:
    branches:
      - main
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment and label
        run: |
          gh pr comment ${{github.event.pull_request.number}} --body "Thank you for your contribution, our team will be reviewing this shortly, please be available for any follow up questions or code review feedback!"

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Label PR based on Changes
        run: |
          echo '${{ steps.file_changes.outputs.files_added}}'
          if [[ '${{ steps.file_changes.outputs.files_added}}' =~ "config.yml" ]]; then
              echo "New config.yml added"
              gh pr edit ${{github.event.pull_request.number}} --add-label "new-quickstart"
          elif [[ '${{ steps.file_changes.outputs.files_modified}}' =~ quickstarts/.* ]]; then
              echo "Quickstart Updated"
              gh pr edit ${{github.event.pull_request.number}} --add-label "improved-quickstart"
          fi
