name: Release

on:
  push:
    branches:
      - main

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  generate-schema-docs:
    name: Generate schema documentation
    needs: [generate-uuid]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          ref: 'main'
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: cd utils/schema-doc-generator && pip install -r requirements.txt

      - name: Generate documentation
        id: generate-docs
        run: python utils/schema-doc-generator/script.py

      - name: Commit changes
        id: commit-changes
        run: |
          git config --local user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
          git config --local user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
          git add ./docs/*
          git diff-index --quiet HEAD ./docs/* || git commit -m 'chore: generate schema documentation [skip ci]'
          echo "::set-output name=commit::true"

      - name: Push Commit
        if: steps.commit-changes.outputs.commit == 'true'
        run: git push origin HEAD

  job-generate-release:
    name: Create Release
    needs: [generate-uuid, generate-schema-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        # Ensure we have the most recent commit to `main`
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Add plugins for semantic release
        run: npm install @semantic-release/git @semantic-release/changelog

      - name: Run semantic-release
        env:
          # Use nr-opensource-bot for authoring commits done by
          # semantic-release (rather than using @semantic-release-bot)
          GIT_AUTHOR_NAME: "nr-opensource-bot"
          GIT_AUTHOR_EMAIL: "opensource+bot@newrelic.com"
          GIT_COMMITTER_NAME: "nr-opensource-bot"
          GIT_COMMITTER_EMAIL: "opensource+bot@newrelic.com"
          GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
        run: npx semantic-release@^18.0.0


